name: Plagiarism Check with MOSS

on:
  workflow_dispatch:
    inputs:
      assignment_org:
        description: 'Name of GH organization to scan'
        required: true
        default: VY-Assignments
      repo_pattern:
        description: 'Repository name pattern to check (regex)'
        required: true
        default: 'asmt-*'
      language:
        description: 'Programming language to check'
        required: true
        default: 'c'
        type: choice
        options:
          - c
          - cc
          - java
          - python
          - javascript

env:
  MOSS_USER_ID: ${{ secrets.MOSS_USER_ID }}

jobs:
  check-plagiarism:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout plagiarism checker repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
          
      - name: Setup MOSS script
        run: chmod +x scripts/moss
          
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Get repository list and clone repositories
        run: |
          mkdir submissions
          cd submissions
          
          for repo in $(gh repo list ${{ inputs.assignment_org }} --json nameWithOwner --jq ".[].nameWithOwner" --limit 1000 | grep "${{inputs.assignment_org}}/${{ inputs.repo_pattern }}"); do
            echo "Cloning $repo"
            git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$repo.git"
          done

          ls -la submissions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run MOSS checker
        run: |
          case "${{ inputs.language }}" in
            "python")
              pattern="*.py"
              ;;
            "java")
              pattern="*.java"
              ;;
            "cc")
              pattern="*.cpp *.h *.c *.hpp"
              ;;
            "c")
              pattern="*.c *.h"
              ;;
            "javascript")
              pattern="*.js"
              ;;
          esac
          
          # Run MOSS and save output to a file
          ./scripts/moss -l ${{ inputs.language }} -d submissions/**/$pattern > moss_results.txt
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: moss-results
          path: moss_results.txt