name: Plagiarism Check with MOSS

on:
  workflow_dispatch:
    inputs:
      assignment_org:
        description: 'Name of GH organization to scan'
        required: true
        default: VY-Assignments
      repo_pattern:
        description: 'Repository name pattern to check (regex)'
        required: true
        default: 'asmt'
      language:
        description: 'Programming language to check'
        required: true
        default: 'cc'
        type: choice
        options:
          - cc
          - c
          - java
          - python
          - javascript

env:
  MOSS_USER_ID: ${{ secrets.MOSS_USER_ID }}

jobs:
  check-plagiarism:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout plagiarism checker repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
          
      - name: Setup MOSS script
        run: chmod +x scripts/moss
          
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
            
      - name: Debug - List repos
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "All repos found:"
          gh repo list ${{ inputs.assignment_org }} --limit 1000 --json nameWithOwner -q '.[].nameWithOwner' | tee repos.txt
          echo "Total repos found: $(cat repos.txt | wc -l)"
          
          echo "Repos after filter:"
          gh repo list ${{ inputs.assignment_org }} --limit 1000 --json nameWithOwner -q '.[].nameWithOwner' | \
          grep -E ${{ inputs.repo_pattern }} | tee filtered-repos.txt
          echo "Total repos to clone: $(cat filtered-repos.txt | wc -l)"

      - name: Get repository list and clone repositories
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir submissions
          cd submissions

          gh repo list ${{ inputs.assignment_org }} --limit 1000 --json nameWithOwner -q '.[].nameWithOwner' | \
          grep -E ${{ inputs.repo_pattern }} | \
          while read -r repo; do
              if [ ! -z "$repo" ]; then
                  echo "Cloning $repo..."
                  gh repo clone "$repo" || echo "Failed to clone $repo"
              fi
          done

          echo "Successfully cloned repositories:"
          ls -la
          cd ..
          
      - name: Run MOSS checker
        run: |
          case "${{ inputs.language }}" in
            "python")
              pattern="submissions/*/*.py"
              ;;
            "java")
              pattern="submissions/*/*.java"
              ;;
            "cc")
              pattern="submissions/*/*.cpp submissions/*/.h"
              ;;
            "c")
              pattern="submissions/*/*.c submissions/*/*.h"
              ;;
            "javascript")
              pattern="submissions/*/*.js"
              ;;
          esac
          
          # Run MOSS and save output to a file
          ./scripts/moss -l ${{ inputs.language }} -d $pattern
